import { Ingredients } from '../interfces';

export const INGREDIENTS: Array<Ingredients> = [
	{
		id: 1,
		title:'сладкий перец',
		optional: true,
		isChosen:true,
	},
	{
		id: 2,
		title: 'куриные кусочки',
		optional: false,
		isChosen:true,
	},
	{
		id: 3,
		title: 'сыр моцарелла',
		optional: true,
		isChosen:true,
	},
	{
		id: 4,
		title: 'красный лук',
		optional: true,
		isChosen:true,
	},
	{
		id: 5,
		title: 'соус чили',
		optional: true,
		isChosen:true,
	},
	{
		id: 6,
		title: 'смесь сыров чеддер и пармезан',
		optional: true,
		isChosen:true,
	},
	{
		id: 7,
		title: 'пепперони',
		optional: false,
		isChosen:true,
	},
	{
		id: 8,
		title: 'пицца-соус',
		optional: false,
		isChosen:true,
	},
	{
		id: 9,
		title: 'пепперони с говядиной',
		optional: false,
		isChosen:true,
	},
	{
		id: 10,
		title: 'сыр моцарелла из цельного молока',
		optional: false,
		isChosen:true,
	},
	{
		id: 11,
		title: 'томатный соус',
		optional: false,
		isChosen:true,
	},
	{
		id: 12,
		title: 'митболы из 100% говядины',
		optional: true,
		isChosen:true,
	},
	{
		id: 13,
		title: 'соленые огурчики',
		optional: true,
		isChosen:true,
	},
	{
		id: 14,
		title: 'томаты',
		optional: true,
		isChosen:true,
	},
	{
		id: 15,
		title: 'сырный соус',
		optional: false,
		isChosen:true,
	},
	{
		id: 16,
		title: 'индейка',
		optional: true,
		isChosen:true,
	},
	{
		id: 17,
		title: 'говядина',
		optional: true,
		isChosen:true,
	},
	{
		id: 18,
		title: 'моцарелла из цельного молока',
		optional: false,
		isChosen:true,
	},
	{
		id: 19,
		title: 'шампиньоны',
		optional: false,
		isChosen:true,
	},
	{
		id: 20,
		title: 'брынза',
		optional: true,
		isChosen:true,
	},
	{
		id: 21,
		title: 'итальянские травы',
		optional: true,
		isChosen:true,
	},
	{
		id: 22,
		title: 'цыпленок',
		optional: true,
		isChosen:true,
	},
	{
		id: 23,
		title: 'увеличенная порция моцареллы из цельного молока',
		optional: false,
		isChosen:true,
	},
	{
		id: 24,
		title: 'ветчина из цыпленка',
		optional: true,
		isChosen:true,
	},
	{
		id: 25,
		title: 'чеснок',
		optional: true,
		isChosen:true,
	},
	{
		id: 26,
		title: 'сыр чеддер',
		optional: true,
		isChosen:true,
	},
	{
		id: 27,
		title: 'ананасы',
		optional: true,
		isChosen:true,
	},
	{
		id: 28,
		title: 'базилик',
		optional: true,
		isChosen:true,
	},
	{
		id: 29,
		title: 'перец халапеньо',
		optional: true,
		isChosen:true,
	},
	{
		id: 30,
		title: 'соус сальса',
		optional: false,
		isChosen:true,
	},
	{
		id: 31,
		title: 'митболы из говядины',
		optional: true,
		isChosen:true,
	},
	{
		id: 32,
		title: 'соус барбекю',
		optional: false,
		isChosen:true,
	},
	{
		id: 32,
		title: 'соус ранч',
		optional: false,
		isChosen:true,
	},
	{
		id: 33,
		title: 'кисло-сладкий соус',
		optional: false,
		isChosen:true,
	},
	{
		id: 34,
		title: 'охотничьи колбаски',
		optional: false,
		isChosen:true,
	},
	{
		id: 35,
		title: 'сыр блю чиз',
		optional: true,
		isChosen:true,
	},
	{
		id:36,
		title: 'сыр пармезан',
		optional: true,
		isChosen:true,
	},
	{
		id: 37,
		title: 'брусника',
		optional: false,
		isChosen:true,
	},
	{
		id: 38,
		title: 'сгущенное молоко',
		optional: false,
		isChosen:true,
	},
]
